### PR TITLE
QEditor Image Sprint

### PR DESCRIPTION
**Pull request by nothingismagick**
### Verify that
- [x] the branch name follows the git flow naming convention (feature/i18n)
- [x] the UT reference is appended to the branch name if it concerns a Jira Task (feature/i18n/UT-283)
- [x] the design is responsive
- [x] the code doesn't break Server Side Rendering
- [x] new functions are prefixed with JSDoc information
- [x] the code doesn't break the api endpoints contract
- [x] JS Standard code style has been verified with ESLint

Please provide a test plan so that the reviewers can see how you tested your work and/or the different acceptance criteria described in the task.

### **Test plan**

_Feature / acceptance criteria tested_

* Step 1 - lerna clean , lerna link , lerna bootstrap 
* Step 2 - Visit /en/articles/create and create a new article
* Step 3a - Drag an image file from the filesystem to the Editor pane, drop it.
* Step 3b - Drag several image files from the filesystem to the Editor pane, drop them.
* Step 3c - Drag a non-image file from the filesystem to the Editor pane, drop it.
* Step 4a - Copy an image file from the filesystem and paste it into the Editor pane 
* Step 4b - Copy several image files from the filesystem and paste them into the Editor pane
* Step 4c - Copy a non-image file from the filesystem and paste it into the Editor pane 
* Step 5a - Click the image button, select a file from the filesystem.
* Step 5b - Click the image button, select multiple images.
* Step 5c - Click the image button, select non-image file. 
* Step 6 - Paste rich text (like from your IDE) into the editor
* Step 7 - "UPDATE THE ARTICLE"
* Step 8 - Reload the page (everything should still be there!)

**Expected result:** You should for each case of 3,4 & 5:
- see an image in the HTML Editor
- see a link in the MD code preview
- see an image in the MD render preview
- not be able to upload a non-image (if that is the scope)

**Extra credit**
- Visit http://localhost:8080/en/croppa
- Upload an image, drag it around the circle and zoom with the scroll wheel
- It is wired up to the IPFS endpoint (click the green button)
- It is buttery smooth on mobile

### CODE REVIEW

**Comment by nothingismagick** [comment]
So this has been tested on:
Mac: Safari, Chrome, Firefox
iOS: Safari
Android: Chrome

**Comment by icaroharry** [comment]
## Review (Chrome - ElementaryOS):

- We need to have a "drop here" state in the UI so the user can know where to drop. Example:
image
- If I accidentally drop the image outside of the editor, it opens the image in the browser, closing the app. The user might lose his editions if this happens.
- 4.a: Copy & paste doesn't work for me. It pastes the local path of the file (same for non images):
image
- 6: copying the README.md from v2.utopian.io in my code editor to the utopian editor causes this:
image
 

## Outside of the scope, but to register:
- Click on "full screen" option -> Click on "markdown preview" -> You can't close the fullscreen mode anymore.

**Comment by nothingismagick** [comment]
So I tried to resolve all of the issues. Other than the file paste not working on windows and linux I think I managed to catch all of them - especially dropping outside of the dropzone...

**Comment by nothingismagick** [comment]
Just in case you forget the rest of the universe:
22bb7595-fa9b-4e10-a63e-bc1556d32c9c

**Comment by nothingismagick** [comment]
https://codepen.io/tech_query/pen/MqGgap
screen shot 2018-11-24 at 13 03 15
image

**Pull request merged**
