### PR TITLE
[WIP] UT-120 Markdown Parser 

### PR DESCRIPTION
**Pull request by tensor-programming**
WIP Please do not merge
markdown-issue

Problem with parser came from image above.  When parsing images in a table, the regex would capture more than one image.  In this image, it is capturing three different images and then putting them into a new HTML image element.  It was also removing the "|" characters for the table and adding a bunch of line breaks which caused the table not to be generated. In the future, it might be worth adding some logic to determine if the images are inside of a table or not.  For now this is a band-aid solution however.

### CODE REVIEW

**Comment by ms10398** [comment]
Hey @tensor-programming ,

Whats the status of the PR.

**Comment by tensor-programming** [comment]
Its still a WIP.  There are a few issues that were not reported that I encountered while working on it and as a result I have to wait until I have more time to sit down and work out the other problems.

**Comment by tensor-programming** [comment]
Accidentally, merged this in my sleepless stupor; It should be fine since it is finished but it needs to be reviewed.

**Comment by icaroharry** [comment]
Reviewed 👁

**Pull request merged**
