### PR TITLE
Feature/work experience/ut 255

### PR DESCRIPTION
**Pull request by eastmaels**
### Verify that
Git checklist
- [x] the branch name follows the git flow naming convention + label + UT reference if applicable (feature/i18n/UT-283)
- [x] I have rebased my branch to develop before submitting my PR

Front end checklist
- [x] the design is responsive
- [x] the code doesn't break Server Side Rendering

API checklist
- [X] the code doesn't break the api endpoints contract (applicable when we're in production and the api is officially open and used by 3rd party app)

Tests and comments checklist
- [x] JS Standard code style has been verified with ESLint
- [x] the pull request contains unit tests for new code that passes and has at least 50% coverage
- [ ] functions are prefixed with JSDoc information or the doc has been updated

---

Please provide a test plan so that the reviewers can see how you tested your work and/or the different acceptance criteria described in the task.

### **Test plan**

_No work experience_

* Go to user profile

**Expected result:** The text : "tell us about your different jobs and projects" should display

_Add new work experience_

* Go to user profile
* Input all required fields
* Click Create

**Expected result:** You should see the new work experience added.

_Edit work experience_

* Go to user profile
* Click Edit on an existing work experience

**Expected result:** You should see the edit form displayed and populated with the selected work experience.

_Update work experience_

* Go to user profile
* Click Edit on an existing work experience
* Update fields
* Click Update

**Expected result:** Updated information is displayed on the work experience list; the edit for is collapsed after update

_Delete work experience_

* Go to user profile
* Click Delete on an existing work experience
* Click Yes

**Expected result:** A confirmation dialog will display on click on Delete; work experience should be removed/delete in the work experience list once "Yes" is clicked on the confirm dialog

_Start date is after end date_

* Go to user profile
* Add new experience (+) button
* Untick 'current' checkbox
* Input 'from' date to be greater than 'to' date

**Expected result:** 'from' date should display as error (red bottom border) and the error 'Start date should be before end date.' should display below the 'from' date

### CODE REVIEW

**Comment by gregory-latinier** [comment]
You had it right the first time for the date component. I think we misunderstood each other. Could rollback to when we had the possibility to choose a year?

**Comment by eastmaels** [comment]
> You had it right the first time for the date component. I think we misunderstood each other. Could rollback to when we had the possibility to choose a year?

I removed the minimal property and returned it to the default design.

**Comment by eastmaels** [comment]
Hello @gregory-latinier, happy holidays. I need help in resolving the last issue regarding this PR - fields not in error state when you click save.

This was working before but I'm not sure what changed. When I focus on the field, it changes to an error state. It seems that when a field is in focus, that's only the time that the field error state displays.

**Comment by eastmaels** [comment]
> Yes you're right, I missed the error color

I already merged the latest codes from develop and confirmed that the field error state has been resolved. Please re-check.

**Comment by gregory-latinier** [comment]
image

The input is too narrow, 
The display in the input doesn't match the one in the card.
Use the format prop of the q-datetime component, add an `"inputShort": "M/D/YYYY"` key in the i18n `formats.dateTime` to solve this issue

**Pull request merged**
